// https://zh.wikipedia.org/wiki/ISO_4217
// https://zh.wikipedia.org/wiki/ISO_3166-1%E4%BA%8C%E4%BD%8D%E5%AD%97%E6%AF%8D%E4%BB%A3%E7%A0%81#%E6%AD%A3%E5%BC%8F%E5%88%86%E9%85%8D%E4%BB%A3%E7%A0%81
export type County = {
    code: string,
    name: string,
    nameEn: string,
    currencyCode: string
}
export const counties = new Map<string, County>([
    ['AL', {'code': 'AL', 'name': '阿尔巴尼亚', 'nameEn': 'Albania', 'currencyCode': 'ALL'}],
    ['DZ', {'code': 'DZ', 'name': '阿尔及利亚', 'nameEn': 'Algeria', 'currencyCode': 'DZD'}],
    ['AF', {'code': 'AF', 'name': '阿富汗', 'nameEn': 'Afghanistan', 'currencyCode': 'AFN'}],
    ['AR', {'code': 'AR', 'name': '阿根廷', 'nameEn': 'Argentina', 'currencyCode': 'ARS'}],
    ['AE', {'code': 'AE', 'name': '阿联酋', 'nameEn': 'United Arab Emirates', 'currencyCode': 'AED'}],
    ['AW', {'code': 'AW', 'name': '阿鲁巴', 'nameEn': 'Aruba', 'currencyCode': 'AWG'}],
    ['OM', {'code': 'OM', 'name': '阿曼', 'nameEn': 'Oman', 'currencyCode': 'OMR'}],
    ['AZ', {'code': 'AZ', 'name': '阿塞拜疆', 'nameEn': 'Azerbaijan', 'currencyCode': 'AZN'}],
    ['EG', {'code': 'EG', 'name': '埃及', 'nameEn': 'Egypt', 'currencyCode': 'EGP'}],
    ['ET', {'code': 'ET', 'name': '埃塞俄比亚', 'nameEn': 'Ethiopia', 'currencyCode': 'ETB'}],
    ['IE', {'code': 'IE', 'name': '爱尔兰', 'nameEn': 'Ireland', 'currencyCode': 'EUR'}],
    ['EE', {'code': 'EE', 'name': '爱沙尼亚', 'nameEn': 'Estonia', 'currencyCode': 'EUR'}],
    ['AD', {'code': 'AD', 'name': '安道尔', 'nameEn': 'Andorra', 'currencyCode': 'EUR'}],
    ['AO', {'code': 'AO', 'name': '安哥拉', 'nameEn': 'Angola', 'currencyCode': 'AOA'}],
    ['AI', {'code': 'AI', 'name': '安圭拉', 'nameEn': 'Anguilla', 'currencyCode': 'XCD'}],
    ['AG', {'code': 'AG', 'name': '安提瓜和巴布达', 'nameEn': 'Antigua and Barbuda', 'currencyCode': 'XCD'}],
    ['AT', {'code': 'AT', 'name': '奥地利', 'nameEn': 'Austria', 'currencyCode': 'EUR'}],
    ['AU', {'code': 'AU', 'name': '澳大利亚', 'nameEn': 'Australia', 'currencyCode': 'AUD'}],
    ['MO', {'code': 'MO', 'name': '澳门', 'nameEn': 'Macao', 'currencyCode': 'MOP'}],
    ['BB', {'code': 'BB', 'name': '巴巴多斯', 'nameEn': 'Barbados', 'currencyCode': 'BBD'}],
    ['PG', {'code': 'PG', 'name': '巴布亚新几内亚', 'nameEn': 'Papua New Guinea', 'currencyCode': 'PGK'}],
    ['BS', {'code': 'BS', 'name': '巴哈马', 'nameEn': 'Bahamas', 'currencyCode': 'BSD'}],
    ['PK', {'code': 'PK', 'name': '巴基斯坦', 'nameEn': 'Pakistan', 'currencyCode': 'PKR'}],
    ['PY', {'code': 'PY', 'name': '巴拉圭', 'nameEn': 'Paraguay', 'currencyCode': 'PYG'}],
    ['PS', {'code': 'PS', 'name': '巴勒斯坦', 'nameEn': 'Palestine, State of', 'currencyCode': 'ILS'}],
    ['BH', {'code': 'BH', 'name': '巴林', 'nameEn': 'Bahrain', 'currencyCode': 'BHD'}],
    ['PA', {'code': 'PA', 'name': '巴拿马', 'nameEn': 'Panama', 'currencyCode': 'PAB'}],
    ['BR', {'code': 'BR', 'name': '巴西', 'nameEn': 'Brazil', 'currencyCode': 'BRL'}],
    ['BY', {'code': 'BY', 'name': '白俄罗斯', 'nameEn': 'Belarus', 'currencyCode': 'BYN'}],
    ['BM', {'code': 'BM', 'name': '百慕大', 'nameEn': 'Bermuda', 'currencyCode': 'BMD'}],
    ['BG', {'code': 'BG', 'name': '保加利亚', 'nameEn': 'Bulgaria', 'currencyCode': 'BGN'}],
    ['MP', {'code': 'MP', 'name': '北马里亚纳群岛', 'nameEn': 'Northern Mariana Islands', 'currencyCode': 'USD'}],
    ['BJ', {'code': 'BJ', 'name': '贝宁', 'nameEn': 'Benin', 'currencyCode': 'XOF'}],
    ['BE', {'code': 'BE', 'name': '比利时', 'nameEn': 'Belgium', 'currencyCode': 'EUR'}],
    ['IS', {'code': 'IS', 'name': '冰岛', 'nameEn': 'Iceland', 'currencyCode': 'ISK'}],
    ['PR', {'code': 'PR', 'name': '波多黎各', 'nameEn': 'Puerto Rico', 'currencyCode': 'USD'}],
    ['BA', {'code': 'BA', 'name': '波黑', 'nameEn': 'Bosnia and Herzegovina', 'currencyCode': 'BAM'}],
    ['PL', {'code': 'PL', 'name': '波兰', 'nameEn': 'Poland', 'currencyCode': 'PLN'}],
    ['BO', {'code': 'BO', 'name': '玻利维亚', 'nameEn': 'Bolivia, Plurinational State of', 'currencyCode': 'BOB'}],
    ['BZ', {'code': 'BZ', 'name': '伯利兹', 'nameEn': 'Belize', 'currencyCode': 'BZD'}],
    ['BW', {'code': 'BW', 'name': '博茨瓦纳', 'nameEn': 'Botswana', 'currencyCode': 'BWP'}],
    ['BT', {'code': 'BT', 'name': '不丹', 'nameEn': 'Bhutan', 'currencyCode': 'BTN'}],
    ['BF', {'code': 'BF', 'name': '布基纳法索', 'nameEn': 'Burkina Faso', 'currencyCode': 'XOF'}],
    ['BI', {'code': 'BI', 'name': '布隆迪', 'nameEn': 'Burundi', 'currencyCode': 'BIF'}],
    ['BV', {'code': 'BV', 'name': '布韦岛', 'nameEn': 'Bouvet Island', 'currencyCode': 'NOK'}],
    ['KP', {'code': 'KP', 'name': '朝鲜', 'nameEn': 'Korea, Democratic People\'s Republic of', 'currencyCode': 'KPW'}],
    ['GQ', {'code': 'GQ', 'name': '赤道几内亚', 'nameEn': 'Equatorial Guinea', 'currencyCode': 'XAF'}],
    ['DK', {'code': 'DK', 'name': '丹麦', 'nameEn': 'Denmark', 'currencyCode': 'DKK'}],
    ['DE', {'code': 'DE', 'name': '德国', 'nameEn': 'Germany', 'currencyCode': 'EUR'}],
    ['TL', {'code': 'TL', 'name': '东帝汶', 'nameEn': 'Timor-Leste', 'currencyCode': 'USD'}],
    ['TG', {'code': 'TG', 'name': '多哥', 'nameEn': 'Togo', 'currencyCode': 'XOF'}],
    ['DO', {'code': 'DO', 'name': '多米尼加', 'nameEn': 'Dominican Republic', 'currencyCode': 'DOP'}],
    ['DM', {'code': 'DM', 'name': '多米尼克', 'nameEn': 'Dominica', 'currencyCode': 'XCD'}],
    ['RU', {'code': 'RU', 'name': '俄罗斯', 'nameEn': 'Russian Federation', 'currencyCode': 'RUB'}],
    ['EC', {'code': 'EC', 'name': '厄瓜多尔', 'nameEn': 'Ecuador', 'currencyCode': 'USD'}],
    ['ER', {'code': 'ER', 'name': '厄立特里亚', 'nameEn': 'Eritrea', 'currencyCode': 'ERN'}],
    ['FR', {'code': 'FR', 'name': '法国', 'nameEn': 'France', 'currencyCode': 'EUR'}],
    ['FO', {'code': 'FO', 'name': '法罗群岛', 'nameEn': 'Faroe Islands', 'currencyCode': 'DKK'}],
    ['PF', {'code': 'PF', 'name': '法属波利尼西亚', 'nameEn': 'French Polynesia', 'currencyCode': 'XPF'}],
    ['VA', {'code': 'VA', 'name': '梵蒂冈', 'nameEn': 'Holy See', 'currencyCode': 'EUR'}],
    ['PH', {'code': 'PH', 'name': '菲律宾', 'nameEn': 'Philippines', 'currencyCode': 'PHP'}],
    ['FJ', {'code': 'FJ', 'name': '斐济', 'nameEn': 'Fiji', 'currencyCode': 'FJD'}],
    ['FI', {'code': 'FI', 'name': '芬兰', 'nameEn': 'Finland', 'currencyCode': 'EUR'}],
    ['CV', {'code': 'CV', 'name': '佛得角', 'nameEn': 'Cabo Verde', 'currencyCode': 'CVE'}],
    ['FK', {'code': 'FK', 'name': '福克兰群岛', 'nameEn': 'Falkland Islands (Malvinas)', 'currencyCode': 'FKP'}],
    ['GM', {'code': 'GM', 'name': '冈比亚', 'nameEn': 'Gambia', 'currencyCode': 'GMD'}],
    ['CG', {'code': 'CG', 'name': '刚果共和国', 'nameEn': 'Congo', 'currencyCode': 'XAF'}],
    ['CD', {'code': 'CD', 'name': '刚果民主共和国', 'nameEn': 'Congo, the Democratic Republic of the', 'currencyCode': 'CDF'}],
    ['CO', {'code': 'CO', 'name': '哥伦比亚', 'nameEn': 'Colombia', 'currencyCode': 'COP'}],
    ['CR', {'code': 'CR', 'name': '哥斯达黎加', 'nameEn': 'Costa Rica', 'currencyCode': 'CRC'}],
    ['GD', {'code': 'GD', 'name': '格林纳达', 'nameEn': 'Grenada', 'currencyCode': 'XCD'}],
    ['GL', {'code': 'GL', 'name': '格陵兰', 'nameEn': 'Greenland', 'currencyCode': 'DKK'}],
    ['GE', {'code': 'GE', 'name': '格鲁吉亚', 'nameEn': 'Georgia', 'currencyCode': 'GEL'}],
    ['GG', {'code': 'GG', 'name': '根西', 'nameEn': 'Guernsey', 'currencyCode': 'GBP'}],
    ['CU', {'code': 'CU', 'name': '古巴', 'nameEn': 'Cuba', 'currencyCode': 'CUP'}],
    ['GP', {'code': 'GP', 'name': '瓜德罗普', 'nameEn': 'Guadeloupe', 'currencyCode': 'EUR'}],
    ['GU', {'code': 'GU', 'name': '关岛', 'nameEn': 'Guam', 'currencyCode': 'USD'}],
    ['GY', {'code': 'GY', 'name': '圭亚那', 'nameEn': 'Guyana', 'currencyCode': 'GYD'}],
    ['KZ', {'code': 'KZ', 'name': '哈萨克斯坦', 'nameEn': 'Kazakhstan', 'currencyCode': 'KZT'}],
    ['HT', {'code': 'HT', 'name': '海地', 'nameEn': 'Haiti', 'currencyCode': 'HTG'}],
    ['KR', {'code': 'KR', 'name': '韩国', 'nameEn': 'Korea, Republic of', 'currencyCode': 'KRW'}],
    ['NL', {'code': 'NL', 'name': '荷兰', 'nameEn': 'Netherlands', 'currencyCode': 'EUR'}],
    ['SX', {'code': 'SX', 'name': '荷属圣马丁', 'nameEn': 'Sint Maarten (Dutch part)', 'currencyCode': 'ANG'}],
    ['HM', {'code': 'HM', 'name': '赫德岛和麦克唐纳群岛', 'nameEn': 'Heard Island and McDonald Islands', 'currencyCode': 'AUD'}],
    ['ME', {'code': 'ME', 'name': '黑山', 'nameEn': 'Montenegro', 'currencyCode': 'EUR'}],
    ['HN', {'code': 'HN', 'name': '洪都拉斯', 'nameEn': 'Honduras', 'currencyCode': 'HNL'}],
    ['KI', {'code': 'KI', 'name': '基里巴斯', 'nameEn': 'Kiribati', 'currencyCode': 'AUD'}],
    ['DJ', {'code': 'DJ', 'name': '吉布提', 'nameEn': 'Djibouti', 'currencyCode': 'DJF'}],
    ['KG', {'code': 'KG', 'name': '吉尔吉斯斯坦', 'nameEn': 'Kyrgyzstan', 'currencyCode': 'KGS'}],
    ['GN', {'code': 'GN', 'name': '几内亚', 'nameEn': 'Guinea', 'currencyCode': 'GNF'}],
    ['GW', {'code': 'GW', 'name': '几内亚比绍', 'nameEn': 'Guinea-Bissau', 'currencyCode': 'XOF'}],
    ['CA', {'code': 'CA', 'name': '加拿大', 'nameEn': 'Canada', 'currencyCode': 'CAD'}],
    ['GH', {'code': 'GH', 'name': '加纳', 'nameEn': 'Ghana', 'currencyCode': 'GHS'}],
    ['GA', {'code': 'GA', 'name': '加蓬', 'nameEn': 'Gabon', 'currencyCode': 'XAF'}],
    ['KH', {'code': 'KH', 'name': '柬埔寨', 'nameEn': 'Cambodia', 'currencyCode': 'KHR'}],
    ['CZ', {'code': 'CZ', 'name': '捷克', 'nameEn': 'Czechia', 'currencyCode': 'CZK'}],
    ['ZW', {'code': 'ZW', 'name': '津巴布韦', 'nameEn': 'Zimbabwe', 'currencyCode': 'ZWL'}],
    ['CM', {'code': 'CM', 'name': '喀麦隆', 'nameEn': 'Cameroon', 'currencyCode': 'XAF'}],
    ['QA', {'code': 'QA', 'name': '卡塔尔', 'nameEn': 'Qatar', 'currencyCode': 'QAR'}],
    ['KY', {'code': 'KY', 'name': '开曼群岛', 'nameEn': 'Cayman Islands', 'currencyCode': 'KYD'}],
    ['CC', {'code': 'CC', 'name': '科科斯（基林）群岛', 'nameEn': 'Cocos (Keeling) Islands', 'currencyCode': 'AUD'}],
    ['KM', {'code': 'KM', 'name': '科摩罗', 'nameEn': 'Comoros', 'currencyCode': 'KMF'}],
    ['CI', {'code': 'CI', 'name': '科特迪瓦', 'nameEn': 'Côte d\'Ivoire', 'currencyCode': 'XOF'}],
    ['KW', {'code': 'KW', 'name': '科威特', 'nameEn': 'Kuwait', 'currencyCode': 'KWD'}],
    ['HR', {'code': 'HR', 'name': '克罗地亚', 'nameEn': 'Croatia', 'currencyCode': 'HRK'}],
    ['KE', {'code': 'KE', 'name': '肯尼亚', 'nameEn': 'Kenya', 'currencyCode': 'KES'}],
    ['CK', {'code': 'CK', 'name': '库克群岛', 'nameEn': 'Cook Islands', 'currencyCode': 'NZD'}],
    ['CW', {'code': 'CW', 'name': '库拉索', 'nameEn': 'Curaçao', 'currencyCode': 'ANG'}],
    ['LV', {'code': 'LV', 'name': '拉脱维亚', 'nameEn': 'Latvia', 'currencyCode': 'EUR'}],
    ['LS', {'code': 'LS', 'name': '莱索托', 'nameEn': 'Lesotho', 'currencyCode': 'LSL'}],
    ['LA', {'code': 'LA', 'name': '老挝', 'nameEn': 'Lao People\'s Democratic Republic', 'currencyCode': 'LAK'}],
    ['LB', {'code': 'LB', 'name': '黎巴嫩', 'nameEn': 'Lebanon', 'currencyCode': 'LBP'}],
    ['LT', {'code': 'LT', 'name': '立陶宛', 'nameEn': 'Lithuania', 'currencyCode': 'EUR'}],
    ['LR', {'code': 'LR', 'name': '利比里亚', 'nameEn': 'Liberia', 'currencyCode': 'LRD'}],
    ['LY', {'code': 'LY', 'name': '利比亚', 'nameEn': 'Libya', 'currencyCode': 'LYD'}],
    ['LI', {'code': 'LI', 'name': '列支敦士登', 'nameEn': 'Liechtenstein', 'currencyCode': 'CHF'}],
    ['RE', {'code': 'RE', 'name': '留尼汪', 'nameEn': 'Réunion', 'currencyCode': 'EUR'}],
    ['LU', {'code': 'LU', 'name': '卢森堡', 'nameEn': 'Luxembourg', 'currencyCode': 'EUR'}],
    ['RW', {'code': 'RW', 'name': '卢旺达', 'nameEn': 'Rwanda', 'currencyCode': 'RWF'}],
    ['RO', {'code': 'RO', 'name': '罗马尼亚', 'nameEn': 'Romania', 'currencyCode': 'RON'}],
    ['MG', {'code': 'MG', 'name': '马达加斯加', 'nameEn': 'Madagascar', 'currencyCode': 'MGA'}],
    ['IM', {'code': 'IM', 'name': '马恩岛', 'nameEn': 'Isle of Man', 'currencyCode': 'GBP'}],
    ['MV', {'code': 'MV', 'name': '马尔代夫', 'nameEn': 'Maldives', 'currencyCode': 'MVR'}],
    ['MT', {'code': 'MT', 'name': '马耳他', 'nameEn': 'Malta', 'currencyCode': 'EUR'}],
    ['MW', {'code': 'MW', 'name': '马拉维', 'nameEn': 'Malawi', 'currencyCode': 'MWK'}],
    ['MY', {'code': 'MY', 'name': '马来西亚', 'nameEn': 'Malaysia', 'currencyCode': 'MYR'}],
    ['ML', {'code': 'ML', 'name': '马里', 'nameEn': 'Mali', 'currencyCode': 'XOF'}],
    ['MH', {'code': 'MH', 'name': '马绍尔群岛', 'nameEn': 'Marshall Islands', 'currencyCode': 'USD'}],
    ['MQ', {'code': 'MQ', 'name': '马提尼克', 'nameEn': 'Martinique', 'currencyCode': 'EUR'}],
    ['YT', {'code': 'YT', 'name': '马约特', 'nameEn': 'Mayotte', 'currencyCode': 'EUR'}],
    ['MU', {'code': 'MU', 'name': '毛里求斯', 'nameEn': 'Mauritius', 'currencyCode': 'MUR'}],
    ['MR', {'code': 'MR', 'name': '毛里塔尼亚', 'nameEn': 'Mauritania', 'currencyCode': 'MRU'}],
    ['US', {'code': 'US', 'name': '美国', 'nameEn': 'United States of America', 'currencyCode': 'USD'}],
    ['AS', {'code': 'AS', 'name': '美属萨摩亚', 'nameEn': 'American Samoa', 'currencyCode': 'USD'}],
    ['VI', {'code': 'VI', 'name': '美属维尔京群岛', 'nameEn': 'Virgin Islands, U.S.', 'currencyCode': 'USD'}],
    ['MN', {'code': 'MN', 'name': '蒙古', 'nameEn': 'Mongolia', 'currencyCode': 'MNT'}],
    ['MS', {'code': 'MS', 'name': '蒙特塞拉特', 'nameEn': 'Montserrat', 'currencyCode': 'XCD'}],
    ['BD', {'code': 'BD', 'name': '孟加拉国', 'nameEn': 'Bangladesh', 'currencyCode': 'BDT'}],
    ['PE', {'code': 'PE', 'name': '秘鲁', 'nameEn': 'Peru', 'currencyCode': 'PEN'}],
    ['FM', {'code': 'FM', 'name': '密克罗尼西亚联邦', 'nameEn': 'Micronesia, Federated States of', 'currencyCode': 'USD'}],
    ['MM', {'code': 'MM', 'name': '缅甸', 'nameEn': 'Myanmar', 'currencyCode': 'MMK'}],
    ['MD', {'code': 'MD', 'name': '摩尔多瓦', 'nameEn': 'Moldova, Republic of', 'currencyCode': 'MDL'}],
    ['MA', {'code': 'MA', 'name': '摩洛哥', 'nameEn': 'Morocco', 'currencyCode': 'MAD'}],
    ['MC', {'code': 'MC', 'name': '摩纳哥', 'nameEn': 'Monaco', 'currencyCode': 'EUR'}],
    ['MZ', {'code': 'MZ', 'name': '莫桑比克', 'nameEn': 'Mozambique', 'currencyCode': 'MZN'}],
    ['MX', {'code': 'MX', 'name': '墨西哥', 'nameEn': 'Mexico', 'currencyCode': 'MXN'}],
    ['NA', {'code': 'NA', 'name': '纳米比亚', 'nameEn': 'Namibia', 'currencyCode': 'NAD'}],
    ['ZA', {'code': 'ZA', 'name': '南非', 'nameEn': 'South Africa', 'currencyCode': 'ZAR'}],
    ['GS', {'code': 'GS', 'name': '南乔治亚和南桑威奇群岛', 'nameEn': 'South Georgia and the South Sandwich Islands', 'currencyCode': 'GBP'}],
    ['SS', {'code': 'SS', 'name': '南苏丹', 'nameEn': 'South Sudan', 'currencyCode': 'SSP'}],
    ['NR', {'code': 'NR', 'name': '瑙鲁', 'nameEn': 'Nauru', 'currencyCode': 'AUD'}],
    ['NI', {'code': 'NI', 'name': '尼加拉瓜', 'nameEn': 'Nicaragua', 'currencyCode': 'NIO'}],
    ['NP', {'code': 'NP', 'name': '尼泊尔', 'nameEn': 'Nepal', 'currencyCode': 'NPR'}],
    ['NG', {'code': 'NG', 'name': '尼日利亚', 'nameEn': 'Nigeria', 'currencyCode': 'NGN'}],
    ['NU', {'code': 'NU', 'name': '纽埃', 'nameEn': 'Niue', 'currencyCode': 'NZD'}],
    ['NO', {'code': 'NO', 'name': '挪威', 'nameEn': 'Norway', 'currencyCode': 'NOK'}],
    ['NF', {'code': 'NF', 'name': '诺福克岛', 'nameEn': 'Norfolk Island', 'currencyCode': 'AUD'}],
    ['PW', {'code': 'PW', 'name': '帕劳', 'nameEn': 'Palau', 'currencyCode': 'USD'}],
    ['PN', {'code': 'PN', 'name': '皮特凯恩群岛', 'nameEn': 'Pitcairn', 'currencyCode': 'NZD'}],
    ['PT', {'code': 'PT', 'name': '葡萄牙', 'nameEn': 'Portugal', 'currencyCode': 'EUR'}],
    ['JP', {'code': 'JP', 'name': '日本', 'nameEn': 'Japan', 'currencyCode': 'JPY'}],
    ['SE', {'code': 'SE', 'name': '瑞典', 'nameEn': 'Sweden', 'currencyCode': 'SEK'}],
    ['CH', {'code': 'CH', 'name': '瑞士', 'nameEn': 'Switzerland', 'currencyCode': 'CHF'}],
    ['SV', {'code': 'SV', 'name': '萨尔瓦多', 'nameEn': 'El Salvador', 'currencyCode': 'USD'}],
    ['WS', {'code': 'WS', 'name': '萨摩亚', 'nameEn': 'Samoa', 'currencyCode': 'WST'}],
    ['RS', {'code': 'RS', 'name': '塞尔维亚', 'nameEn': 'Serbia', 'currencyCode': 'RSD'}],
    ['SL', {'code': 'SL', 'name': '塞拉利昂', 'nameEn': 'Sierra Leone', 'currencyCode': 'SLL'}],
    ['SN', {'code': 'SN', 'name': '塞内加尔', 'nameEn': 'Senegal', 'currencyCode': 'XOF'}],
    ['CY', {'code': 'CY', 'name': '塞浦路斯', 'nameEn': 'Cyprus', 'currencyCode': 'EUR'}],
    ['SC', {'code': 'SC', 'name': '塞舌尔', 'nameEn': 'Seychelles', 'currencyCode': 'SCR'}],
    ['SA', {'code': 'SA', 'name': '沙特阿拉伯', 'nameEn': 'Saudi Arabia', 'currencyCode': 'SAR'}],
    ['BL', {'code': 'BL', 'name': '圣巴泰勒米', 'nameEn': 'Saint Barthélemy', 'currencyCode': 'EUR'}],
    ['CX', {'code': 'CX', 'name': '圣诞岛', 'nameEn': 'Christmas Island', 'currencyCode': 'AUD'}],
    ['ST', {'code': 'ST', 'name': '圣多美和普林西比', 'nameEn': 'Sao Tome and Principe', 'currencyCode': 'STN'}],
    ['SH', {'code': 'SH', 'name': '圣赫勒拿、阿森松和特里斯坦-达库尼亚', 'nameEn': 'Saint Helena, Ascension and Tristan da Cunha', 'currencyCode': 'SHP'}],
    ['KN', {'code': 'KN', 'name': '圣基茨和尼维斯', 'nameEn': 'Saint Kitts and Nevis', 'currencyCode': 'XCD'}],
    ['LC', {'code': 'LC', 'name': '圣卢西亚', 'nameEn': 'Saint Lucia', 'currencyCode': 'XCD'}],
    ['SM', {'code': 'SM', 'name': '圣马力诺', 'nameEn': 'San Marino', 'currencyCode': 'EUR'}],
    ['PM', {'code': 'PM', 'name': '圣皮埃尔和密克隆', 'nameEn': 'Saint Pierre and Miquelon', 'currencyCode': 'EUR'}],
    ['VC', {'code': 'VC', 'name': '圣文森特和格林纳丁斯', 'nameEn': 'Saint Vincent and the Grenadines', 'currencyCode': 'XCD'}],
    ['LK', {'code': 'LK', 'name': '斯里兰卡', 'nameEn': 'Sri Lanka', 'currencyCode': 'LKR'}],
    ['SK', {'code': 'SK', 'name': '斯洛伐克', 'nameEn': 'Slovakia', 'currencyCode': 'EUR'}],
    ['SI', {'code': 'SI', 'name': '斯洛文尼亚', 'nameEn': 'Slovenia', 'currencyCode': 'EUR'}],
    ['SJ', {'code': 'SJ', 'name': '斯瓦尔巴和扬马延', 'nameEn': 'Svalbard and Jan Mayen', 'currencyCode': 'NOK'}],
    ['SZ', {'code': 'SZ', 'name': '斯威士兰', 'nameEn': 'Eswatini', 'currencyCode': 'SZL'}],
    ['SD', {'code': 'SD', 'name': '苏丹', 'nameEn': 'Sudan', 'currencyCode': 'SDG'}],
    ['SR', {'code': 'SR', 'name': '苏里南', 'nameEn': 'Suriname', 'currencyCode': 'SRD'}],
    ['SB', {'code': 'SB', 'name': '所罗门群岛', 'nameEn': 'Solomon Islands', 'currencyCode': 'SBD'}],
    ['SO', {'code': 'SO', 'name': '索马里', 'nameEn': 'Somalia', 'currencyCode': 'SOS'}],
    ['TJ', {'code': 'TJ', 'name': '塔吉克斯坦', 'nameEn': 'Tajikistan', 'currencyCode': 'TJS'}],
    ['TH', {'code': 'TH', 'name': '泰国', 'nameEn': 'Thailand', 'currencyCode': 'THB'}],
    ['TZ', {'code': 'TZ', 'name': '坦桑尼亚', 'nameEn': 'Tanzania, United Republic of', 'currencyCode': 'TZS'}],
    ['TO', {'code': 'TO', 'name': '汤加', 'nameEn': 'Tonga', 'currencyCode': 'TOP'}],
    ['TC', {'code': 'TC', 'name': '特克斯和凯科斯群岛', 'nameEn': 'Turks and Caicos Islands', 'currencyCode': 'USD'}],
    ['TT', {'code': 'TT', 'name': '特立尼达和多巴哥', 'nameEn': 'Trinidad and Tobago', 'currencyCode': 'TTD'}],
    ['TN', {'code': 'TN', 'name': '突尼斯', 'nameEn': 'Tunisia', 'currencyCode': 'TND'}],
    ['TV', {'code': 'TV', 'name': '图瓦卢', 'nameEn': 'Tuvalu', 'currencyCode': 'AUD'}],
    ['TR', {'code': 'TR', 'name': '土耳其', 'nameEn': 'Turkey', 'currencyCode': 'TRY'}],
    ['TM', {'code': 'TM', 'name': '土库曼斯坦', 'nameEn': 'Turkmenistan', 'currencyCode': 'TMT'}],
    ['TK', {'code': 'TK', 'name': '托克劳', 'nameEn': 'Tokelau', 'currencyCode': 'NZD'}],
    ['WF', {'code': 'WF', 'name': '瓦利斯和富图纳', 'nameEn': 'Wallis and Futuna', 'currencyCode': 'XPF'}],
    ['VU', {'code': 'VU', 'name': '瓦努阿图', 'nameEn': 'Vanuatu', 'currencyCode': 'VUV'}],
    ['GT', {'code': 'GT', 'name': '危地马拉', 'nameEn': 'Guatemala', 'currencyCode': 'GTQ'}],
    ['VE', {'code': 'VE', 'name': '委内瑞拉', 'nameEn': 'Venezuela, Bolivarian Republic of', 'currencyCode': 'VES'}],
    ['BN', {'code': 'BN', 'name': '文莱', 'nameEn': 'Brunei Darussalam', 'currencyCode': 'BND'}],
    ['UG', {'code': 'UG', 'name': '乌干达', 'nameEn': 'Uganda', 'currencyCode': 'UGX'}],
    ['UA', {'code': 'UA', 'name': '乌克兰', 'nameEn': 'Ukraine', 'currencyCode': 'UAH'}],
    ['UY', {'code': 'UY', 'name': '乌拉圭', 'nameEn': 'Uruguay', 'currencyCode': 'UYU'}],
    ['UZ', {'code': 'UZ', 'name': '乌兹别克斯坦', 'nameEn': 'Uzbekistan', 'currencyCode': 'UZS'}],
    ['ES', {'code': 'ES', 'name': '西班牙', 'nameEn': 'Spain', 'currencyCode': 'EUR'}],
    ['GR', {'code': 'GR', 'name': '希腊', 'nameEn': 'Greece', 'currencyCode': 'EUR'}],
    ['SG', {'code': 'SG', 'name': '新加坡', 'nameEn': 'Singapore', 'currencyCode': 'SGD'}],
    ['NC', {'code': 'NC', 'name': '新喀里多尼亚', 'nameEn': 'New Caledonia', 'currencyCode': 'XPF'}],
    ['NZ', {'code': 'NZ', 'name': '新西兰', 'nameEn': 'New Zealand', 'currencyCode': 'NZD'}],
    ['HU', {'code': 'HU', 'name': '匈牙利', 'nameEn': 'Hungary', 'currencyCode': 'HUF'}],
    ['SY', {'code': 'SY', 'name': '叙利亚', 'nameEn': 'Syrian Arab Republic', 'currencyCode': 'SYP'}],
    ['JM', {'code': 'JM', 'name': '牙买加', 'nameEn': 'Jamaica', 'currencyCode': 'JMD'}],
    ['AM', {'code': 'AM', 'name': '亚美尼亚', 'nameEn': 'Armenia', 'currencyCode': 'AMD'}],
    ['YE', {'code': 'YE', 'name': '也门', 'nameEn': 'Yemen', 'currencyCode': 'YER'}],
    ['IQ', {'code': 'IQ', 'name': '伊拉克', 'nameEn': 'Iraq', 'currencyCode': 'IQD'}],
    ['IR', {'code': 'IR', 'name': '伊朗', 'nameEn': 'Iran, Islamic Republic of', 'currencyCode': 'IRR'}],
    ['IL', {'code': 'IL', 'name': '以色列', 'nameEn': 'Israel', 'currencyCode': 'ILS'}],
    ['IT', {'code': 'IT', 'name': '意大利', 'nameEn': 'Italy', 'currencyCode': 'EUR'}],
    ['IN', {'code': 'IN', 'name': '印度', 'nameEn': 'India', 'currencyCode': 'INR'}],
    ['ID', {'code': 'ID', 'name': '印度尼西亚', 'nameEn': 'Indonesia', 'currencyCode': 'IDR'}],
    ['GB', {'code': 'GB', 'name': '英国', 'nameEn': 'United Kingdom of Great Britain and Northern Ireland', 'currencyCode': 'GBP'}],
    ['VG', {'code': 'VG', 'name': '英属维尔京群岛', 'nameEn': 'Virgin Islands, British', 'currencyCode': 'USD'}],
    ['IO', {'code': 'IO', 'name': '英属印度洋领地', 'nameEn': 'British Indian Ocean Territory', 'currencyCode': 'GBP'}],
    ['IO', {'code': 'IO', 'name': '英属印度洋领地', 'nameEn': 'British Indian Ocean Territory', 'currencyCode': 'USD'}],
    ['JO', {'code': 'JO', 'name': '约旦', 'nameEn': 'Jordan', 'currencyCode': 'JOD'}],
    ['VN', {'code': 'VN', 'name': '越南', 'nameEn': 'Viet Nam', 'currencyCode': 'VND'}],
    ['ZM', {'code': 'ZM', 'name': '赞比亚', 'nameEn': 'Zambia', 'currencyCode': 'ZMW'}],
    ['JE', {'code': 'JE', 'name': '泽西', 'nameEn': 'Jersey', 'currencyCode': 'GBP'}],
    ['TD', {'code': 'TD', 'name': '乍得', 'nameEn': 'Chad', 'currencyCode': 'XAF'}],
    ['GI', {'code': 'GI', 'name': '直布罗陀', 'nameEn': 'Gibraltar', 'currencyCode': 'GIP'}],
    ['CL', {'code': 'CL', 'name': '智利', 'nameEn': 'Chile', 'currencyCode': 'CLF'}],
    ['CL', {'code': 'CL', 'name': '智利', 'nameEn': 'Chile', 'currencyCode': 'CLP'}],
    ['CF', {'code': 'CF', 'name': '中非', 'nameEn': 'Central African Republic', 'currencyCode': 'XAF'}],
    ['CN', {'code': 'CN', 'name': '中国', 'nameEn': 'China', 'currencyCode': 'CNY'}],
    ['TW', {'code': 'TW', 'name': '中国台湾', 'nameEn': 'Taiwan, Province of China', 'currencyCode': 'TWD'}],
    ['HK', {'code': 'HK', 'name': '中国香港', 'nameEn': 'Hong Kong', 'currencyCode': 'HKD'}]
])
