export type County = {
    countyCode: string,
    name: string,
    currencyCode: string
}
export const counties = new Map<string, County>([
    ['AF', {'countyCode': 'AF', 'name': 'Afghanistan', 'currencyCode': 'AFN'}],
    ['AL', {'countyCode': 'AL', 'name': 'Albania', 'currencyCode': 'ALL'}],
    ['AR', {'countyCode': 'AR', 'name': 'Argentina', 'currencyCode': 'ARS'}],
    ['AW', {'countyCode': 'AW', 'name': 'Aruba', 'currencyCode': 'AWG'}],
    ['AU', {'countyCode': 'AU', 'name': 'Australia', 'currencyCode': 'AUD'}],
    ['AZ', {'countyCode': 'AZ', 'name': 'Azerbaijan', 'currencyCode': 'AZN'}],
    ['BS', {'countyCode': 'BS', 'name': 'Bahamas', 'currencyCode': 'BSD'}],
    ['BB', {'countyCode': 'BB', 'name': 'Barbados', 'currencyCode': 'BBD'}],
    ['BY', {'countyCode': 'BY', 'name': 'Belarus', 'currencyCode': 'BYR'}],
    ['BZ', {'countyCode': 'BZ', 'name': 'Belize', 'currencyCode': 'BZD'}],
    ['BM', {'countyCode': 'BM', 'name': 'Bermuda', 'currencyCode': 'BMD'}],
    ['BO', {'countyCode': 'BO', 'name': 'Bolivia', 'currencyCode': 'BOB'}],
    ['BA', {'countyCode': 'BA', 'name': 'Bosnia and Herzegovina', 'currencyCode': 'BAM'}],
    ['BW', {'countyCode': 'BW', 'name': 'Botswana', 'currencyCode': 'BWP'}],
    ['BR', {'countyCode': 'BR', 'name': 'Brazil', 'currencyCode': 'BRL'}],
    ['BN', {'countyCode': 'BN', 'name': 'Brunei', 'currencyCode': 'BND'}],
    ['BG', {'countyCode': 'BG', 'name': 'Bulgaria', 'currencyCode': 'BGN'}],
    ['KH', {'countyCode': 'KH', 'name': 'Cambodia', 'currencyCode': 'KHR'}],
    ['CA', {'countyCode': 'CA', 'name': 'Canada', 'currencyCode': 'CAD'}],
    ['CL', {'countyCode': 'CL', 'name': 'Chile', 'currencyCode': 'CLP'}],
    ['CN', {'countyCode': 'CN', 'name': 'China', 'currencyCode': 'CNY'}],
    ['CO', {'countyCode': 'CO', 'name': 'Colombia', 'currencyCode': 'COP'}],
    ['CR', {'countyCode': 'CR', 'name': 'Costa Rica', 'currencyCode': 'CRC'}],
    ['HR', {'countyCode': 'HR', 'name': 'Croatia', 'currencyCode': 'HRK'}],
    ['CU', {'countyCode': 'CU', 'name': 'Cuba', 'currencyCode': 'CUP'}],
    ['CZ', {'countyCode': 'CZ', 'name': 'Czech Republic', 'currencyCode': 'CZK'}],
    ['DK', {'countyCode': 'DK', 'name': 'Denmark', 'currencyCode': 'DKK'}],
    ['DO', {'countyCode': 'DO', 'name': 'Dominican Republic', 'currencyCode': 'DOP'}],
    ['EG', {'countyCode': 'EG', 'name': 'Egypt', 'currencyCode': 'EGP'}],
    ['SV', {'countyCode': 'SV', 'name': 'El Salvador', 'currencyCode': 'SVC'}],
    ['EE', {'countyCode': 'EE', 'name': 'Estonia', 'currencyCode': 'EEK'}],
    ['FK', {'countyCode': 'FK', 'name': 'Falkland Islands', 'currencyCode': 'FKP'}],
    ['FJ', {'countyCode': 'FJ', 'name': 'Fiji', 'currencyCode': 'FJD'}],
    ['GE', {'countyCode': 'GE', 'name': 'Georgia', 'currencyCode': 'GEL'}],
    ['GH', {'countyCode': 'GH', 'name': 'Ghana', 'currencyCode': 'GHC'}],
    ['GI', {'countyCode': 'GI', 'name': 'Gibraltar', 'currencyCode': 'GIP'}],
    ['GT', {'countyCode': 'GT', 'name': 'Guatemala', 'currencyCode': 'GTQ'}],
    ['GG', {'countyCode': 'GG', 'name': 'Guernsey', 'currencyCode': 'GGP'}],
    ['GY', {'countyCode': 'GY', 'name': 'Guyana', 'currencyCode': 'GYD'}],
    ['HN', {'countyCode': 'HN', 'name': 'Honduras', 'currencyCode': 'HNL'}],
    ['HK', {'countyCode': 'HK', 'name': 'Hong Kong', 'currencyCode': 'HKD'}],
    ['HU', {'countyCode': 'HU', 'name': 'Hungary', 'currencyCode': 'HUF'}],
    ['IS', {'countyCode': 'IS', 'name': 'Iceland', 'currencyCode': 'ISK'}],
    ['IN', {'countyCode': 'IN', 'name': 'India', 'currencyCode': 'INR'}],
    ['ID', {'countyCode': 'ID', 'name': 'Indonesia', 'currencyCode': 'IDR'}],
    ['IR', {'countyCode': 'IR', 'name': 'Iran', 'currencyCode': 'IRR'}],
    ['IM', {'countyCode': 'IM', 'name': 'Isle of Man', 'currencyCode': 'IMP'}],
    ['IL', {'countyCode': 'IL', 'name': 'Israel', 'currencyCode': 'ILS'}],
    ['JM', {'countyCode': 'JM', 'name': 'Jamaica', 'currencyCode': 'JMD'}],
    ['JP', {'countyCode': 'JP', 'name': 'Japan', 'currencyCode': 'JPY'}],
    ['JE', {'countyCode': 'JE', 'name': 'Jersey', 'currencyCode': 'JEP'}],
    ['KZ', {'countyCode': 'KZ', 'name': 'Kazakhstan', 'currencyCode': 'KZT'}],
    ['KG', {'countyCode': 'KG', 'name': 'Kyrgyzstan', 'currencyCode': 'KGS'}],
    ['LA', {'countyCode': 'LA', 'name': 'Laos', 'currencyCode': 'LAK'}],
    ['LV', {'countyCode': 'LV', 'name': 'Latvia', 'currencyCode': 'LVL'}],
    ['LB', {'countyCode': 'LB', 'name': 'Lebanon', 'currencyCode': 'LBP'}],
    ['LR', {'countyCode': 'LR', 'name': 'Liberia', 'currencyCode': 'LRD'}],
    ['LT', {'countyCode': 'LT', 'name': 'Lithuania', 'currencyCode': 'LTL'}],
    ['MK', {'countyCode': 'MK', 'name': 'Macedonia', 'currencyCode': 'MKD'}],
    ['MY', {'countyCode': 'MY', 'name': 'Malaysia', 'currencyCode': 'MYR'}],
    ['MU', {'countyCode': 'MU', 'name': 'Mauritius', 'currencyCode': 'MUR'}],
    ['MX', {'countyCode': 'MX', 'name': 'Mexico', 'currencyCode': 'MXN'}],
    ['MN', {'countyCode': 'MN', 'name': 'Mongolia', 'currencyCode': 'MNT'}],
    ['MZ', {'countyCode': 'MZ', 'name': 'Mozambique', 'currencyCode': 'MZN'}],
    ['NA', {'countyCode': 'NA', 'name': 'Namibia', 'currencyCode': 'NAD'}],
    ['NP', {'countyCode': 'NP', 'name': 'Nepal', 'currencyCode': 'NPR'}],
    ['NL', {'countyCode': 'NL', 'name': 'Netherlands', 'currencyCode': 'ANG'}],
    ['NZ', {'countyCode': 'NZ', 'name': 'New Zealand', 'currencyCode': 'NZD'}],
    ['NI', {'countyCode': 'NI', 'name': 'Nicaragua', 'currencyCode': 'NIO'}],
    ['NG', {'countyCode': 'NG', 'name': 'Nigeria', 'currencyCode': 'NGN'}],
    ['NO', {'countyCode': 'NO', 'name': 'Norway', 'currencyCode': 'NOK'}],
    ['OM', {'countyCode': 'OM', 'name': 'Oman', 'currencyCode': 'OMR'}],
    ['PK', {'countyCode': 'PK', 'name': 'Pakistan', 'currencyCode': 'PKR'}],
    ['PA', {'countyCode': 'PA', 'name': 'Panama', 'currencyCode': 'PAB'}],
    ['PY', {'countyCode': 'PY', 'name': 'Paraguay', 'currencyCode': 'PYG'}],
    ['PE', {'countyCode': 'PE', 'name': 'Peru', 'currencyCode': 'PEN'}],
    ['PH', {'countyCode': 'PH', 'name': 'Philippines', 'currencyCode': 'PHP'}],
    ['PL', {'countyCode': 'PL', 'name': 'Poland', 'currencyCode': 'PLN'}],
    ['QA', {'countyCode': 'QA', 'name': 'Qatar', 'currencyCode': 'QAR'}],
    ['RO', {'countyCode': 'RO', 'name': 'Romania', 'currencyCode': 'RON'}],
    ['RU', {'countyCode': 'RU', 'name': 'Russia', 'currencyCode': 'RUB'}],
    ['SH', {'countyCode': 'SH', 'name': 'Saint Helena', 'currencyCode': 'SHP'}],
    ['SA', {'countyCode': 'SA', 'name': 'Saudi Arabia', 'currencyCode': 'SAR'}],
    ['RS', {'countyCode': 'RS', 'name': 'Serbia', 'currencyCode': 'RSD'}],
    ['SC', {'countyCode': 'SC', 'name': 'Seychelles', 'currencyCode': 'SCR'}],
    ['SG', {'countyCode': 'SG', 'name': 'Singapore', 'currencyCode': 'SGD'}],
    ['SB', {'countyCode': 'SB', 'name': 'Solomon Islands', 'currencyCode': 'SBD'}],
    ['SO', {'countyCode': 'SO', 'name': 'Somalia', 'currencyCode': 'SOS'}],
    ['ZA', {'countyCode': 'ZA', 'name': 'South Africa', 'currencyCode': 'ZAR'}],
    ['LK', {'countyCode': 'LK', 'name': 'Sri Lanka', 'currencyCode': 'LKR'}],
    ['SR', {'countyCode': 'SR', 'name': 'Suriname', 'currencyCode': 'SRD'}],
    ['SE', {'countyCode': 'SE', 'name': 'Sweden', 'currencyCode': 'SEK'}],
    ['CH', {'countyCode': 'CH', 'name': 'Switzerland', 'currencyCode': 'CHF'}],
    ['SY', {'countyCode': 'SY', 'name': 'Syria', 'currencyCode': 'SYP'}],
    ['TW', {'countyCode': 'TW', 'name': 'Taiwan', 'currencyCode': 'TWD'}],
    ['TH', {'countyCode': 'TH', 'name': 'Thailand', 'currencyCode': 'THB'}],
    ['TT', {'countyCode': 'TT', 'name': 'Trinidad and Tobago', 'currencyCode': 'TTD'}],
    ['TR', {'countyCode': 'TR', 'name': 'Turkey', 'currencyCode': 'TRL'}],
    ['TV', {'countyCode': 'TV', 'name': 'Tuvalu', 'currencyCode': 'TVD'}],
    ['UA', {'countyCode': 'UA', 'name': 'Ukraine', 'currencyCode': 'UAH'}],
    ['GB', {'countyCode': 'GB', 'name': 'United Kingdom', 'currencyCode': 'GBP'}],
    ['US', {'countyCode': 'US', 'name': 'United States', 'currencyCode': 'USD'}],
    ['UY', {'countyCode': 'UY', 'name': 'Uruguay', 'currencyCode': 'UYU'}],
    ['UZ', {'countyCode': 'UZ', 'name': 'Uzbekistan', 'currencyCode': 'UZS'}],
    ['VE', {'countyCode': 'VE', 'name': 'Venezuela', 'currencyCode': 'VEF'}],
    ['YE', {'countyCode': 'YE', 'name': 'Yemen', 'currencyCode': 'YER'}],
    ['ZW', {'countyCode': 'ZW', 'name': 'Zimbabwe', 'currencyCode': 'ZWD'}],
    ['KR', {'countyCode': 'KR', 'name': 'South Korea', 'currencyCode': 'KRW'}],
    ['KP', {'countyCode': 'KR', 'name': 'North Korea', 'currencyCode': 'KPW'}],
])
